apiVersion: apps/v1
kind: Deployment
metadata:
  name: narrativelog
  labels:
    app: narrativelog
spec:
  replicas: 1
  selector:
    matchLabels:
      name: narrativelog
  template:
    metadata:
      labels:
        name: narrativelog
    spec:
      containers:
        - name: app
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/narrativelog"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: narrativelog
