apiVersion: v1
kind: Service
metadata:
  name: narrativelog
  labels:
    app: narrativelog
spec:
  ports:
    - name: narrativelog-http
      protocol: TCP
      port: 8080
      targetPort: app
  selector:
    name: narrativelog
